on: [pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: jaiodoo/odoo-actions@v1.2.3
      with:
        python-root: '.'
        flake8-flags: '--ignore=F401 --max-line-length=80'
        skip-flake8: ''
